"""fix error

Revision ID: 3188a8c56394
Revises: d1aaee7a6ea5
Create Date: 2024-05-15 15:16:26.591016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3188a8c56394'
down_revision = 'd1aaee7a6ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.VARCHAR(), nullable=True))
    op.drop_column('messages', 'username')
    # ### end Alembic commands ###
