"""fix another error

Revision ID: a3134746c847
Revises: 3188a8c56394
Create Date: 2024-05-15 15:17:21.950009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3134746c847'
down_revision = '3188a8c56394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
